name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ contains(matrix.ruby-version, 'head') }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', ruby, head, jruby, jruby-head, truffleruby, truffleruby-head]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Build
        run: gem build petrovich.gemspec
      - name: Run tests
        run: rake
      - name: Run evaluation
        run: rake evaluate
